### ISSUE TITLE
Initial Editor Checklist

### ISSUE THREAD

**Issue by jsndyks** [journalovi/2024-Dueck-neighborhood-traces#1]
- [x] Check that the HTML version is in the repo as index.html and renders to the JoVI format (refer to https://github.com/journalovi/jovi-template-quarto)
- [x] ~~Article uses a format something similar to the template~~
- [x] Includes author information
- [x] Includes abstract
- [x] Includes the required paper sections
   - [x] ~~Table of contents~~
   - [x] Research materials
   - [x] Authorship
   - [x] License
   - [x] Conflicts of Interest
- [ ] ~~All figures have alt texts that describe the content non-visually~~
- [x] Add a notice infobox at the top that the paper is under review w/ link to github issues above the abstract. In Quarto this looks like:
   ```
   ::: {.callout-important appearance="simple"}
   ## Under Review {.unnumbered}
   This paper is under review on the experimental track of the [Journal of Visualization and Interaction](https://www.journalovi.org/).
   :::
   ```
- [x] ~~Set up github pages~~
   - [x] ~~Settings -> Actions -> General -> Allow journalovi, and select non-journalovi, actions. Enter:~~ 
      ~~`actions/*,quarto-dev/*`~~
      ![image](https://github.com/journalovi/2023-park-gatherplots/assets/6345019/05018b2f-f00e-4019-92de-cced0aab0d72)
   - [x] ~~If using Quarto:~~
      - [x] ~~clone the repo locally~~
      - [x] ~~run this command in the repo directory:~~
         ```
         quarto publish gh-pages index.qmd
         ```
- [x] From the main repo page, click the settings gear icon next to "About" on the right. 
   - [x] Under "Description" enter "UNDER REVIEW"
   - [x] Under "Website" tick "Use Your Github Pages Website".
- [x] ~~Verify the publishing workflow works. On the repo page, go to Actions and click on the "XXX Publish" (XXX = Quarto/Idyll/etc) workflow on the left, then click Run Workflow and run it.~~
   - [x] ~~When this completes, check that the "pages build and deployment" action is successful.~~
   - [x] Check that the article is visible at the github.io address.
- [x] Edit README.md and add the following at the very top:
   ````
   ```diff
   ! This paper is under review on the experimental track of the Journal of Visualization and Interaction.
   ```
   ````
- [x] Ensure all appropriate supplemental materials are included: e.g. experimental data, experimental analysis code, source code for artifacts, etc. For a full list of requirements see the [transparency section of the author guide](https://www.journalovi.org/author-guide.html#transparency-requirements)
  - [x] Check they are in appropriate long-term repositories (e.g. OSF, Zenodo, etc). Github repositories are okay as long as they are also archived on something like OSF or Zenodo. One easy way to archive + DOI an existing github repo is with Zenodo; see [here](https://docs.github.com/en/repositories/archiving-a-github-repository/referencing-and-citing-content)
  - [x] Check they are listed in the abstract and the required Materials section of the paper
- [x] ~~If anything in the above list is missing (required paper sections, supplemental materials, etc), create an issue tagging the authors and ask them to add those materials (do this after sending them the intial review email).~~

**Comment by jsndyks** [comment]
Completed with @chatchavan - all looks OK for now.

**Comment by chatchavan** [comment]
@chatchavan For the unchecked points above, the checklist itself needs to be updated.

**Comment by eaganj** [comment]
I have been nominated as the new AE for this submission.
